/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.wildtaxi.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Message service. Represents a row in the &quot;wt_Message&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.sareweb.wildtaxi.model.impl.MessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.sareweb.wildtaxi.model.impl.MessageImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a message model instance should use the {@link Message} interface instead.
 * </p>
 *
 * @author Sareweb
 * @see Message
 * @see net.sareweb.wildtaxi.model.impl.MessageImpl
 * @see net.sareweb.wildtaxi.model.impl.MessageModelImpl
 * @generated
 */
public interface MessageModel extends BaseModel<Message> {
	/**
	 * Gets the primary key of this message.
	 *
	 * @return the primary key of this message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this message
	 *
	 * @param pk the primary key of this message
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the uuid of this message.
	 *
	 * @return the uuid of this message
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this message.
	 *
	 * @param uuid the uuid of this message
	 */
	public void setUuid(String uuid);

	/**
	 * Gets the message id of this message.
	 *
	 * @return the message id of this message
	 */
	public long getMessageId();

	/**
	 * Sets the message id of this message.
	 *
	 * @param messageId the message id of this message
	 */
	public void setMessageId(long messageId);

	/**
	 * Gets the offer id of this message.
	 *
	 * @return the offer id of this message
	 */
	public long getOfferId();

	/**
	 * Sets the offer id of this message.
	 *
	 * @param offerId the offer id of this message
	 */
	public void setOfferId(long offerId);

	/**
	 * Gets the message of this message.
	 *
	 * @return the message of this message
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this message.
	 *
	 * @param message the message of this message
	 */
	public void setMessage(String message);

	/**
	 * Gets the company id of this message.
	 *
	 * @return the company id of this message
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this message.
	 *
	 * @param companyId the company id of this message
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this message.
	 *
	 * @return the user id of this message
	 */
	public long getUserId();

	/**
	 * Sets the user id of this message.
	 *
	 * @param userId the user id of this message
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this message.
	 *
	 * @return the user uuid of this message
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this message.
	 *
	 * @param userUuid the user uuid of this message
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the create date of this message.
	 *
	 * @return the create date of this message
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this message.
	 *
	 * @param createDate the create date of this message
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets a copy of this message as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public Message toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Message message);

	public int hashCode();

	public String toString();

	public String toXmlString();
}