/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package net.sareweb.wildtaxi.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import net.sareweb.wildtaxi.model.Offer;
import net.sareweb.wildtaxi.model.OfferModel;
import net.sareweb.wildtaxi.model.OfferSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the Offer service. Represents a row in the &quot;wt_Offer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link net.sareweb.wildtaxi.model.OfferModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OfferImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a offer model instance should use the {@link net.sareweb.wildtaxi.model.Offer} interface instead.
 * </p>
 *
 * @author Sareweb
 * @see OfferImpl
 * @see net.sareweb.wildtaxi.model.Offer
 * @see net.sareweb.wildtaxi.model.OfferModel
 * @generated
 */
public class OfferModelImpl extends BaseModelImpl<Offer> implements OfferModel {
	public static final String TABLE_NAME = "wt_Offer";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", new Integer(Types.VARCHAR) },
			{ "offerId", new Integer(Types.BIGINT) },
			{ "requestId", new Integer(Types.BIGINT) },
			{ "state", new Integer(Types.VARCHAR) },
			{ "agreementKey", new Integer(Types.VARCHAR) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "createDate", new Integer(Types.TIMESTAMP) }
		};
	public static final String TABLE_SQL_CREATE = "create table wt_Offer (uuid_ VARCHAR(75) null,offerId LONG not null primary key,requestId LONG,state VARCHAR(75) null,agreementKey VARCHAR(75) null,companyId LONG,userId LONG,createDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table wt_Offer";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.net.sareweb.wildtaxi.model.Offer"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.net.sareweb.wildtaxi.model.Offer"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Offer toModel(OfferSoap soapModel) {
		Offer model = new OfferImpl();

		model.setUuid(soapModel.getUuid());
		model.setOfferId(soapModel.getOfferId());
		model.setRequestId(soapModel.getRequestId());
		model.setState(soapModel.getState());
		model.setAgreementKey(soapModel.getAgreementKey());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Offer> toModels(OfferSoap[] soapModels) {
		List<Offer> models = new ArrayList<Offer>(soapModels.length);

		for (OfferSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.net.sareweb.wildtaxi.model.Offer"));

	public OfferModelImpl() {
	}

	public long getPrimaryKey() {
		return _offerId;
	}

	public void setPrimaryKey(long pk) {
		setOfferId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_offerId);
	}

	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	public void setUuid(String uuid) {
		_uuid = uuid;
	}

	public long getOfferId() {
		return _offerId;
	}

	public void setOfferId(long offerId) {
		_offerId = offerId;
	}

	public long getRequestId() {
		return _requestId;
	}

	public void setRequestId(long requestId) {
		_requestId = requestId;
	}

	public String getState() {
		if (_state == null) {
			return StringPool.BLANK;
		}
		else {
			return _state;
		}
	}

	public void setState(String state) {
		_state = state;
	}

	public String getAgreementKey() {
		if (_agreementKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _agreementKey;
		}
	}

	public void setAgreementKey(String agreementKey) {
		_agreementKey = agreementKey;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Offer toEscapedModel() {
		if (isEscapedModel()) {
			return (Offer)this;
		}
		else {
			return (Offer)Proxy.newProxyInstance(Offer.class.getClassLoader(),
				new Class[] { Offer.class }, new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					Offer.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		OfferImpl offerImpl = new OfferImpl();

		offerImpl.setUuid(getUuid());

		offerImpl.setOfferId(getOfferId());

		offerImpl.setRequestId(getRequestId());

		offerImpl.setState(getState());

		offerImpl.setAgreementKey(getAgreementKey());

		offerImpl.setCompanyId(getCompanyId());

		offerImpl.setUserId(getUserId());

		offerImpl.setCreateDate(getCreateDate());

		return offerImpl;
	}

	public int compareTo(Offer offer) {
		long pk = offer.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Offer offer = null;

		try {
			offer = (Offer)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = offer.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", offerId=");
		sb.append(getOfferId());
		sb.append(", requestId=");
		sb.append(getRequestId());
		sb.append(", state=");
		sb.append(getState());
		sb.append(", agreementKey=");
		sb.append(getAgreementKey());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("net.sareweb.wildtaxi.model.Offer");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>offerId</column-name><column-value><![CDATA[");
		sb.append(getOfferId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestId</column-name><column-value><![CDATA[");
		sb.append(getRequestId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>state</column-name><column-value><![CDATA[");
		sb.append(getState());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>agreementKey</column-name><column-value><![CDATA[");
		sb.append(getAgreementKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private String _uuid;
	private long _offerId;
	private long _requestId;
	private String _state;
	private String _agreementKey;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private transient ExpandoBridge _expandoBridge;
}